"""Render repo-root example notebooks into MkDocs example pages.

The executable notebooks under ``examples/*.ipynb`` are the source of truth for
worked example recipes. This hook writes the MkDocs-facing markdown pages under
``docs/examples/*.md`` before each docs build.
"""

from __future__ import annotations

import json
import pathlib
from collections.abc import Mapping
from typing import Any

_REPO_ROOT = pathlib.Path(__file__).parent.parent.parent
_NOTEBOOK_DIR = _REPO_ROOT / "examples"
_OUT_DIR = _REPO_ROOT / "docs" / "examples"


def iter_example_notebooks() -> list[pathlib.Path]:
    """Return the notebooks that render into docs example pages."""
    return sorted(_NOTEBOOK_DIR.glob("*.ipynb"))


def output_path_for(notebook_path: pathlib.Path) -> pathlib.Path:
    """Return the generated docs path for ``notebook_path``."""
    return _OUT_DIR / f"{notebook_path.stem}.md"


def render_notebook(notebook_path: pathlib.Path) -> str:
    """Render one notebook to a MkDocs markdown page."""
    notebook = json.loads(notebook_path.read_text(encoding="utf-8"))
    cells = notebook.get("cells", [])
    title = _page_title(cells, fallback=notebook_path.stem.replace("_", " ").title())
    source_rel = notebook_path.relative_to(_REPO_ROOT).as_posix()

    parts = [
        "---\n",
        f"title: {title}\n",
        "---\n\n",
        f"<!-- Generated from {source_rel}. Do not edit this file directly. -->\n\n",
        f"Source notebook: [`{source_rel}`]"
        f"(https://github.com/awwesomeman/factrix/blob/main/{source_rel}).\n\n",
    ]

    stripped_title = False
    for cell in cells:
        cell_type = cell.get("cell_type")
        if cell_type == "markdown":
            text, did_strip = _render_markdown_cell(
                cell, strip_title=not stripped_title
            )
            stripped_title = stripped_title or did_strip
            if text:
                parts.append(text)
        elif cell_type == "code":
            text = _render_code_cell(cell)
            if text:
                parts.append(text)

    return "".join(parts).rstrip() + "\n"


def generate() -> None:
    """Generate all docs example pages from their notebooks."""
    notebooks = iter_example_notebooks()
    _OUT_DIR.mkdir(parents=True, exist_ok=True)
    for notebook_path in notebooks:
        out_path = output_path_for(notebook_path)
        out_path.write_text(render_notebook(notebook_path), encoding="utf-8")
        print(
            "render_example_notebooks: "
            f"wrote {out_path.relative_to(_REPO_ROOT).as_posix()}"
        )


def on_pre_build(config: object) -> None:
    """MkDocs hook: regenerate example pages before every build."""
    generate()


def _page_title(cells: list[Mapping[str, Any]], *, fallback: str) -> str:
    for cell in cells:
        if cell.get("cell_type") != "markdown":
            continue
        for line in _cell_text(cell).splitlines():
            if line.startswith("# "):
                return line.removeprefix("# ").strip()
            if line.strip():
                break
    return fallback


def _render_markdown_cell(
    cell: Mapping[str, Any], *, strip_title: bool
) -> tuple[str, bool]:
    text = _cell_text(cell).rstrip()
    if not text:
        return "", False

    stripped = False
    if strip_title:
        lines = text.splitlines()
        if lines and lines[0].startswith("# "):
            text = "\n".join(lines[1:]).lstrip()
            stripped = True

    if not text:
        return "", stripped
    return f"{text}\n\n", stripped


def _render_code_cell(cell: Mapping[str, Any]) -> str:
    source = _cell_text(cell).rstrip()
    parts: list[str] = []
    if source:
        parts.append(f"```python\n{source}\n```\n\n")

    for output in cell.get("outputs", []):
        output_text = _output_text(output).rstrip()
        if output_text:
            parts.append(f"```text\n{output_text}\n```\n\n")

    return "".join(parts)


def _output_text(output: Mapping[str, Any]) -> str:
    output_type = output.get("output_type")
    if output_type == "stream":
        return _as_text(output.get("text"))
    if output_type in {"execute_result", "display_data"}:
        data = output.get("data", {})
        if isinstance(data, Mapping):
            return _as_text(data.get("text/plain"))
    if output_type == "error":
        traceback = output.get("traceback")
        if isinstance(traceback, list):
            return "\n".join(str(line) for line in traceback)
        ename = output.get("ename", "Error")
        evalue = output.get("evalue", "")
        return f"{ename}: {evalue}".rstrip()
    return ""


def _cell_text(cell: Mapping[str, Any]) -> str:
    return _as_text(cell.get("source"))


def _as_text(value: object) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return "".join(str(item) for item in value)
    return ""


if __name__ == "__main__":
    generate()
